apiVersion: v1
kind: Pod
metadata:
  name: post-install-pod
  annotations:
    "helm.sh/hook": post-install
spec:
  containers:
    - name: post-install-container
      image: busybox
      command: ['sh', '-c', 'echo Post-install hook executed; sleep 30']
  restartPolicy: Never

