apiVersion: v1
kind: Pod
metadata:
  name: pre-install-pod
  annotations:
    "helm.sh/hook": pre-install
spec:
  containers:
    - name: pre-install-container
      image: busybox
      command: ['sh', '-c', 'echo Pre-install hook executed; sleep 30']
  restartPolicy: Never

